name: BAF
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python = 3.12.9
  - snakemake-minimal = 9.1.7
  - matplotlib = 3.10.0
  - pandas = 2.2.3
  - openpyxl = 3.1.5
  - geopandas = 1.0.1
  - scipy = 1.15.2
  - plotly = 6.0.0
  - click = 8.1.8
  - numpy = 2.2.3
  - tsam = 2.3.6
  - pip
  - pip:
    - rpy2 == 3.5.11
    - pybalmorel == 0.5.3
    - ipython == 9.1.0
    - ptyprocess == 0.7.0
    - ipykernel == 6.29.5
    - pyzmq == 26.4.0
    - premailer == 3.10.0