name: BAF
channels:
  - conda-forge
dependencies:
  - matplotlib == 3.10.0
  - pandas == 2.2.3
  - openpyxl == 3.1.5
  - geopandas == 1.0.1
  - scipy == 1.15.2
  - plotly == 6.0.0
  - click == 8.1.8
  - numpy == 2.2.3
  - tsam == 2.3.6
  - pip
  - pip:
    - pybalmorel == 0.5.3
    - rpy2 == 3.5.11