[workspace]
channels = ["conda-forge", "bioconda"]
name = "BAF"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]
generate-mappings = "cd src && python Pre-Processing/preprocessing.py generate-mappings"
generate-antares-vre = "cd src && pixi run python Pre-Processing/preprocessing.py generate-antares-vre"
generate-balmorel-timeseries = "cd src && pixi run python Pre-Processing/preprocessing.py generate-balmorel-timeseries"
generate-balmorel-hydro = "cd src && python Pre-Processing/preprocessing.py generate-balmorel-hydro"

[target.win.tasks]
R = "cmd /c %USERPROFILE%\\AppData\\Local\\Programs\\R\\R-4.2.3\\bin\\x64\\R"

[dependencies]
snakemake-minimal = ">=9.1.7,<10"
matplotlib = ">=3.10.0"
pandas = ">=2.2.3"
openpyxl = ">=3.1.5"
geopandas = ">=1.0.1"
scipy = ">=1.15.2"
plotly = ">=6.0.0"
click = ">=8.1.8"
numpy = ">=2.2.3"
python = ">=3.12.9"
tsam = ">=2.3.6"

[pypi-dependencies]
rpy2 = "==3.5.11"
pybalmorel = ">=0.5.3, <0.6"
